### ISSUE TITLE
URL Parsing getting stuck for non clickable URL 

### ISSUE THREAD

**Issue by vinay1984** [robinst/autolink-java#24]
Hi Author,

I love this frame work it very nice and robust. I recently came across  parsing non clickable URL resulting partial URL .

Can  you suggest any workaround for this issue 

input : https://us[.]quarantine[.]abc[.]com/notify/
Output : https://us

**Comment by robinst** [comment]
I just pushed a test case for this and it works as expected, see commit 40f18ae.

Can you post the full code that you're using? Maybe something else is wrong.

**Comment by vinay1984** [comment]
we had hidden html content. that html had wrong partial url in href.  please close this ticket it`s working as expected

**Comment by robinst** [comment]
Ok, good to hear!
