### ISSUE TITLE
Extract Phone numbers (request) 

### ISSUE THREAD

**Issue by DastanIqbal** [robinst/autolink-java#28]
No doubts this library is great, I would appreciate your effort or time to write this library. 

but is it possible to have phone number or mobile number extraction features. 

~ Thanks

**Comment by robinst** [comment]
Hey, thanks :)! I don't have any plans to add that.

I think phone numbers might be something where regexes might not be a bad option, so not sure it fits in with the design of this library.

I'll close this but if anyone else is interested in phone numbers, feel free to comment.
