### ISSUE TITLE
Some url without http and www domain

### ISSUE THREAD

**Issue by wangsuicheng** [robinst/autolink-java#37]
This kind of link doesn't work, for example:   github.com/robinst/autolink-java/

**Comment by robinst** [comment]
Yeah that's currently not supported. There is an issue for this with some discussion in the Rust implementation: https://github.com/robinst/linkify/issues/7

Whatever we end up with there could be adapted and added to autolink-java.

**Comment by robinst** [comment]
Oh and there's already an issue for this here: https://github.com/robinst/autolink-java/issues/30
